export default function TermsOfServicePage() {
  return (
    <section className="content-page">
      <h1>Terms of Service</h1>

      <h2>Acceptable use</h2>
      <p>Only submit repositories you own or have write access to, and only repositories with
         a valid RefactorFirst report. Do not attempt to abuse, flood or disrupt the service.</p>

      <h2>Content moderation</h2>
      <p>Repository listings may be removed at the maintainers&apos; discretion, including for
         inappropriate content or abuse.</p>

      <h2>No warranty</h2>
      <p>The service is provided &ldquo;as is&rdquo;, without warranty of any kind. Reports are
         generated by the RefactorFirst tool and rendered as-is from each repository.</p>

      <h2>Limitation of liability</h2>
      <p>To the maximum extent permitted by law, the maintainers are not liable for damages
         arising from use of this service.</p>

      <h2>DMCA</h2>
      <p>To report content that infringes your rights, open an issue in the RefactorFirst
         repository with details of the claim.</p>
    </section>
  );
}
